Zachterrell57/update hashing signing
farcasterxyz/playground pull request #34
Opened 2022-06-18 18:40 UTC by zachterrell57

2022-06-23 22:02 UTC, varunsrin requested changes
Looks great! 

I left some feedback on some refactors that would make this more readable and perhaps reduce some instances of async calls that can be safely avoided.

2022-06-23 22:37 UTC, zachterrell57 commented on src/debugger.ts
> +      console.log(username);
I reverted it but then cherry-picked the changes back onto my commit, I'm not sure why it didn't commit that change as well

2022-06-23 22:40 UTC, zachterrell57 commented on src/engine/engine.reaction.test.ts
> +    const privateKeyBuffer = publicPrivateKeys.get(username)?.get('privateKey') as Uint8Array;
the ed library is very particular about wanting uint8 values, I tried to keep it all hex but the ed library rejected it

2022-06-23 22:43 UTC, zachterrell57 commented on src/utils.ts
> +export const convertToHex = async (text: Uint8Array): Promise<string> => {
I want to say I tried this and it resulted in cryptic error from `ed` in relation to the byte sequence, so I decided to keep all functions within the `ed` ecosystem. Your overall point still stands, but in this particular instance having this function be async does not increase async calls anywhere else since every function that calls this method is async iirc

2022-06-23 22:45 UTC, zachterrell57 commented on src/utils.test.ts
> +  const blake2bSimpleObject =
Yes I replicated it in replit

2022-06-30 18:18 UTC, sds reviewed
This is a much nicer refactoring, nice work! Minor comment about a lingering rebase conflict marker, and some thoughts on how to further refactor (but not a blocker).

2022-06-30 18:18 UTC, sds commented on yarn.lock
> +<<<<<<< HEAD
This looks like a rebase conflict marker. One simple approach if you don't want to address is to remove your `yarn.lock` and just run `yarn install` again to generate a new one. This could result in other changes but given the nature of this repo that's likely fine.

2022-06-30 18:18 UTC, sds commented on src/client.ts
> +    item.signature = await signEd25519(item.hash, this.privateKey);
Something to consider to make this code more flexible to changes in signature implementation in future would be to make your `KeyPair` type a class instead, and define a ed25519 implementation (`Ed25519KeyPair extends KeyPair`) with a `sign`/`verify` methods that you can call.

This allows you to write the rest of the simulator code without the simulator needing to be aware of the underlying algorithm. All the simulator needs to do is work with `KeyPair`s which implement the `sign` and `verify` methods, and then the rest of the code takes care of itself.

2022-07-01 00:35 UTC, varunsrin commented on src/client.ts
> +    item.signature = await signEd25519(item.hash, this.privateKey);
i like this suggestion a lot

2022-07-01 00:44 UTC, varunsrin requested changes

2022-07-01 00:44 UTC, varunsrin commented on src/engine/engine.cast.test.ts
> +    alicePrivateKey = await convertToHex(privateKeyBuffer);
nit: i would add some line breaks so this is a bit easier to parse

2022-07-01 00:44 UTC, varunsrin commented on src/engine/index.ts
> +      if (!(await this.validateMessage(cast)).isOk()) {
this is a bit hard to read since there are so many clauses, i would recommend splitting into a separate line and using the isErr() method to avoid the negation.  

```suggestion
     const isCastValidResult = await this.validateMessage(cast); 
      if (isCastValidResult.isErr()) {
```

2022-07-01 00:44 UTC, varunsrin commented on src/engine/index.ts
> +      console.error(e);
if you want to keep log lines because they are useful for debugging, i would add some method context so its easier for the reader to see. something like: 

```suggestion
      console.error(`engine.MergeCast` + e.toString());
```

2022-07-01 00:44 UTC, varunsrin commented on src/engine/index.ts
> +      if (!(await this.validateMessage(reaction)).isOk()) {
same comment as above about simplifying the clause

2022-07-01 15:54 UTC, varunsrin approved these changes

2022-07-01 15:54 UTC, merged

2022-07-01 15:54 UTC, varunsrin commented
nice work @zachterrell57!